version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: blog_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
  server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
